apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-mysql-kb.fullname" . }}
  labels:
    {{- include "flask-mysql-kb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "flask-mysql-kb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flask-mysql-kb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: flask-mysql-kb
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "flask-mysql-kb.fullname" . }}-configmap
            - secretRef:
                name: {{ include "flask-mysql-kb.fullname" . }}-secret
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
