apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-mysql-kb.fullname" . }}-secret
type: Opaque
data:
  DATABASE_URL: {{ printf "mysql+pymysql://root:%s@%s:%s/%s" .Values.mysql.auth.rootPassword "flask-mysql-kb-mysql-service.flask-mysql-kb.svc.cluster.local" "3306" .Values.mysql.auth.database | b64enc }}