apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-mysql-kb.fullname" . }}-mysql-service
  labels:
    {{- include "flask-mysql-kb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    {{- include "flask-mysql-kb.selectorLabels" . | nindent 4 }}


