apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-mysql-kb.fullname" . }}-mysql-secret
  labels:
    {{- include "flask-mysql-kb.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}





