apiVersion: v1
kind: Service
metadata:
  name: mysql-container
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-mysql-kb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "flask-mysql-kb.name" . }}

